vim.o.termguicolors = true
require("plugin_configs.alpha")
require("plugin_configs.lualine")
require("plugin_configs.tsitter")
require("plugin_configs.toggleterm")
require("plugin_configs.nvim-tree")
require("plugin_configs.modicator")
require("plugin_configs.mason")
require("plugin_configs.nvim-cmp")
require("plugin_configs.wilderness")
require("plugin_configs.comment")
require("plugin_configs.rust")
require("plugin_configs.neogit")
-- require("plugin_configs.colors")
-- require("plugin_configs.jaq")
-- vim.cmd("autocmd VimEnter * TSEnable highlight")

-- themes

-- require("plugin_configs.material")
-- require("plugin_configs.nightfox")
-- require("plugin_configs.kanagawa")
-- require("plugin_configs.rosepine")
-- require("plugin_configs.nord")
require("plugin_configs.onenord")
-- require("plugin_configs.poimandres")
-- require("plugin_configs.everforest")
-- require("plugin_configs.gruvbox")
